p2/Controllers/CookieCountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace p2.Controllers
{
    public class CookieCountController : Controller
    {
        // GET: CookieCount
        public ActionResult Index()
        {
            int count = 1;
            var cookie = Request.Cookies["count"];
            if (cookie == null)
            {
                Response.Cookies.Add(new HttpCookie("count", "1"));
            }
            else
            {
                count = int.Parse(cookie.Value) + 1;
                var newcookie = new HttpCookie("count", count.ToString());
                newcookie.Expires = DateTime.Now.AddMinutes(40);
                Response.Cookies.Add(newcookie);
            }
            ViewBag.count = count;
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult PostLogin(string username,string password)
        {
            if (username=="hello"&&password=="world")
            {
                var cookie = new HttpCookie("isauth", "true");
                Response.Cookies.Add(cookie);
                return RedirectToAction("AddArticle", "Blog");
            }
            return View();
        }
    }
}

p2/Views/CookieCount/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>CookiesCount</h2>
<h3>您是第 @ViewBag.count 次访问此页</h3>

p2/Views/CookieCount/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>登录</h2>
<!--
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Login", "CookieCount"))
        {
            <input type="text" name="account" class="form-control" />
            @Html.Password("password",null,new { @class = "form-control" })
            <button>登录</button>
        }
    </div>
</div>
-->

<form action="@Url.Action("PostLogin")" method="post">
    <table class="table table-bordered">
        <tr>
            <td>用户名</td>
            <td><input type="text" name="username" value="" />  </td>
        </tr>
        <tr>
            <td>密码</td>
            <td><input type="text" name="password" value="" />  </td>
        </tr>
        <tr>  
            <td></td>         
            <td>
                <button type="submit" class="btn btn-primary">登录</button>
            </td>
        </tr>

    </table>
</form>